-- 한줄 주석
/* 범위 주석 */
-- SQL 한 줄 실행 : CRTL + ENTER

/* SYS 관리자 계정으로 수행하는 SQL */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER KH_LYS IDENTIFIED BY KH1234;

GRANT RESOURCE, CONNECT TO KH_LYS;

ALTER USER KH_LYS DEFAULT TABLESPACE USERS QUOTA 20M ON USERS